name: ${pom.name}
main: tigeax.customwings.CustomWings
author: Tigeax
version: ${pom.version}
api-version: 1.13
softdepend:
  - Vault
  - TokenManager
permissions:
  customwings.command:
    deflaut: op
